version: "3"
services:
  app:
    container_name: "switch_friend_clear"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/root/.gitconfig
    command: sleep infinity
